title: Wedding Season

timezone: Europe/Copenhagen

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            author: "Alexandra Timoficiuc"
            author_url: "https://www.instagram.com/tim.alexa/"
            permalink: /blog/:year/:month/:title/

liquid:
    error_mode: strict
    strict_filters: true
    strict_variables: false
